import type { NextPage } from 'next'
import Head from 'next/head'

import { Dashboard } from '../screens/Dashboard';

import { Container } from '../styles/styles.index'

const Home: NextPage = () => {

  return (
    <Container>
      <Head>
        <title>sr.money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashboard />
    </Container>
  )
}

export default Home
